import { CREATE_USER, CURRENT_USER, FOLLOW_TO_USER, GET_ALL_USERS, GET_SINGLE_USER, LOGIN_USER } from "./api"

export const REQUEST = {
  CREATE_USER,
  LOGIN_USER,
  CURRENT_USER,
  FOLLOW_TO_USER,
  GET_ALL_USERS,
  GET_SINGLE_USER
}